server:
  port: 8081

spring:

  application:
    name: PRODUCT-SERVICE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql : true
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: '1234'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka